### ISSUE TITLE
Browser doesn't open to enter user credentials.

### ISSUE THREAD

**Issue by sajonCC** [nesto-software/openvpn3-applet#2]
Hi,

Thank you for your applet. I'm really happy to find this out. 

I do have one issue. When I click connect, browser doesn't open to enter user credentials. Can you please tell me how can I troubleshoot this problem?

I'm on Ubuntu 22.04 with 5.19.0.46-generic kernel, running latest KDE wayland session.

Thank you in advance.

**Comment by MartinLoeper** [comment]
@SinBirb There was some Wayland/XWayland limitation wasn't there?

One thing you could do is to start the applet manually on the cli and see if an error is logged. I believe the applet chooses the browser to open using the $BROWSER env var. You could check whether it is set correctly.

**Comment by sajonCC** [comment]
@MartinLoeper Can you please confirm that $BROWSER variable is used? In my system it is empty. When starting applet from cli and trying to connect I do not receive any error message except this:
`Session path: /net/openvpn/v3/sessions/ccfffb95se1das4aafsbfd3sa8f9a1ccdce2
Auth User name: ** ERROR **   Empty input not allowed`

**Comment by MartinLoeper** [comment]
I see two things here:

- This applet is just a wrapper around the openvpn3 binaries. I would first try to make those binaries work using the official docs, i.e. creating a session on the CLI as follows: https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux#Startingaone-shotconfigurationprofile

- The openvpn3 service will try to authenticate you. The procedure depends on which vpn server you are trying to connect to. Is it OpenVPN CloudConnexa? Is it using SAML for auth? If an interactive web login is required to complete the session setup, I believe you need the BROWSER variable set to firefox or chrome or whatever browser you are using. You can simply export it from your user's .bashrc file in the user home directory. Otherwise openvpn3 does not know which UI to open to prompt you for credentials.

Hope that helps

**Comment by sajonCC** [comment]
Answering your questions:
1. Connection is working from the command line. While connecting, I'm requested to type in user name and password. After which connection is working just fine.
2. I've set BROWSER variable to firefox. Still the same message.

**Comment by MartinLoeper** [comment]
Thanks for the additional information.
From what you are saying, I assume that you are not using SAML authentication or not using the managed OpenVPN service "CloudConnexa".

If that is the case, I conclude this applet only works for browser-based SAML authentication at the moment. We should add it to the README.

Can you confirm that you are entering username and password on the command-line when using openvpn3 binaries directly and that no browser is spawned?

**Comment by sajonCC** [comment]
Ok, clear. It is confirmed, I typing username and password in the command-line. No browser is called.

Do you have a plan to add SAML authentication to your applet?

**Comment by MartinLoeper** [comment]
Unfortunately no, as we wrote this plugin primarily to support the OpenVPN CloudConnexa offering for enterprises. Our company depends on the SAML authentication but we do not plan to provide support for all other authentication methods. Anyway thanks for bringing this issue to our attention!
